const cst = {
    ADD_INSTRUCTOR: "ADD_INSTRUCTOR",
    ADD_INSTRUCTOR_SUCCESS: "ADD_INSTRUCTOR_SUCCESS",
    ADD_INSTRUCTOR_FAILURE: "ADD_INSTRUCTOR_FAILURE",

    ADD_STUDENT: "ADD_STUDENT",
    ADD_STUDENT_SUCCESS: "ADD_STUDENT_SUCCESS",
    ADD_STUDENT_FAILURE: "ADD_STUDENT_FAILURE",

    ADD_DEPARTMENT: "ADD_DEPARTMENT",
    ADD_DEPARTMENT_SUCCESS: "ADD_DEPARTMENT_SUCCESS",
    ADD_DEPARTMENT_FAILURE: "ADD_DEPARTMENT_FAILURE",

    ADD_COURSE: "ADD_COURSE",
    ADD_COURSE_SUCCESS: "ADD_COURSE_SUCCESS",
    ADD_COURSE_FAILURE: "ADD_COURSE_FAILURE",

    ADD_INSTRUCTOR_COURSE: "ADD_INSTRUCTOR_COURSE",
    ADD_INSTRUCTOR_COURSE_SUCCESS: "ADD_INSTRUCTOR_COURSE_SUCCESS",
    ADD_INSTRUCTOR_COURSE_FAILURE: "ADD_INSTRUCTOR_COURSE_FAILURE",

    ADD_STUDENT_COURSE: "ADD_STUDENT_COURSE",
    ADD_STUDENT_COURSE_SUCCESS: "ADD_STUDENT_COURSE_SUCCESS",
    ADD_STUDENT_COURSE_FAILURE: "ADD_STUDENT_COURSE_FAILURE",

    GET_STUDENT_BY_ID: "",

    GET_STUDENTS: "",

    GET_INSTRUCTOR_BY_ID: "",

    GET_INSTRUCTORS: "",

    GET_COURSE_BY_ID: "",

    GET_COURSES: "",

    GET_DEPARTMENT_BY_ID: "",

    GET_DEPARTMENTS: "",

    SET_COURSE_ONSITE: "SET_COURSE_ONSITE",
    SET_COURSE_ONSITE_SUCCESS: "SET_COURSE_ONSITE_SUCCESS",
    SET_COURSE_ONSITE_FAILURE: "SET_COURSE_ONSITE_FAILURE",

    SET_COURSE_ONLINE: "SET_COURSE_ONLINE",
    SET_COURSE_ONLINE_SUCCESS: "SET_COURSE_ONLINE_SUCCESS",
    SET_COURSE_ONLINE_FAILURE: "SET_COURSE_ONLINE_FAILURE",

    UPDATE_STUDENT_GRADE: "UPDATE_STUDENT_GRADE",
    UPDATE_STUDENT_GRADE_SUCCESS: "UPDATE_STUDENT_GRADE_SUCCESS",
    UPDATE_STUDENT_GRADE_FAILURE: "UPDATE_STUDENT_GRADE_FAILURE",

    DELETE_DPT: "DELETE_DPT",
    DELETE_DPT_SUCCESS: "DELETE_DPT_SUCCESS",
    DELETE_DPT_FAILURE: "DELETE_DPT_FAILURE",

    DELETE_INSTRUCTOR: "DELETE_INSTRUCTOR",
    DELETE_INSTRUCTOR_SUCCESS: "DELETE_INSTRUCTOR_SUCCESS",
    DELETE_INSTRUCTOR_FAILURE: "DELETE_INSTRUCTOR_FAILURE",

    DELETE_STUDENT: "DELETE_STUDENT",
    DELETE_STUDENT_SUCCESS: "DELETE_STUDENT_SUCCESS",
    DELETE_STUDENT_FAILURE: "DELETE_STUDENT_FAILURE",

    DELETE_COURSE: "DELETE_COURSE",
    DELETE_COURSE_SUCCESS: "DELETE_COURSE_SUCCESS",
    DELETE_COURSE_FAILURE: "DELETE_COURSE_FAILURE",
    
    MENU_ADD: "MENU_ADD",
    MENU_DISPLAY: "MENU_DISPLAY",
}

export default cst