const cst = {
    ADD_INSTRUCTOR: "ADD_INSTRUCTOR",
    ADD_INSTRUCTOR_SUCCESS: "ADD_INSTRUCTOR_SUCCESS",
    
    ADD_STUDENT: "ADD_STUDENT",
    ADD_STUDENT_SUCCESS: "ADD_STUDENT_SUCCESS",
    
    ADD_DEPARTMENT: "ADD_DEPARTMENT",
    ADD_DEPARTMENT_SUCCESS: "ADD_DEPARTMENT_SUCCESS",
    
    ADD_COURSE: "ADD_COURSE",
    ADD_COURSE_SUCCESS: "ADD_COURSE_SUCCESS",
    
    ADD_INSTRUCTOR_COURSE: "ADD_INSTRUCTOR_COURSE",
    ADD_INSTRUCTOR_COURSE_SUCCESS: "ADD_INSTRUCTOR_COURSE_SUCCESS",
    
    ADD_STUDENT_COURSE: "ADD_STUDENT_COURSE",
    ADD_STUDENT_COURSE_SUCCESS: "ADD_STUDENT_COURSE_SUCCESS",
    
    GET_STUDENT_BY_ID: "GET_STUDENT_BY_ID",
    GET_STUDENT_BY_ID_SUCCESS: "GET_STUDENT_BY_ID_SUCCESS",
    
    GET_STUDENTS: "GET_STUDENTS",
    GET_STUDENTS_SUCCESS: "GET_STUDENTS_SUCCESS",
    
    GET_INSTRUCTOR_BY_ID: "GET_INSTRUCTOR_BY_ID",
    GET_INSTRUCTOR_BY_ID_SUCCESS: "GET_INSTRUCTOR_BY_ID_SUCCESS",
    
    GET_INSTRUCTORS: "GET_INSTRUCTORS",
    GET_INSTRUCTORS_SUCCESS: "GET_INSTRUCTORS_SUCCESS",
    
    GET_COURSE_BY_ID: "GET_COURSE_BY_ID",
    GET_COURSE_BY_ID_SUCCESS: "GET_COURSE_BY_ID_SUCCESS",
    
    GET_COURSES: "GET_COURSES",
    GET_COURSES_SUCCESS: "GET_COURSES_SUCCESS",
    
    GET_DEPARTMENT_BY_ID: "GET_DEPARTMENT_BY_ID",
    GET_DEPARTMENT_BY_ID_SUCCESS: "GET_DEPARTMENT_BY_ID_SUCCESS",
    
    GET_DEPARTMENTS: "GET_DEPARTMENTS",
    GET_DEPARTMENTS_SUCCESS: "GET_DEPARTMENTS_SUCCESS",
    
    SET_COURSE_ONSITE: "SET_COURSE_ONSITE",
    SET_COURSE_ONSITE_SUCCESS: "SET_COURSE_ONSITE_SUCCESS",
    
    SET_COURSE_ONLINE: "SET_COURSE_ONLINE",
    SET_COURSE_ONLINE_SUCCESS: "SET_COURSE_ONLINE_SUCCESS",
    
    UPDATE_STUDENT_GRADE: "UPDATE_STUDENT_GRADE",
    UPDATE_STUDENT_GRADE_SUCCESS: "UPDATE_STUDENT_GRADE_SUCCESS",
    
    DELETE_DPT: "DELETE_DPT",
    DELETE_DPT_SUCCESS: "DELETE_DPT_SUCCESS",
    
    DELETE_INSTRUCTOR: "DELETE_INSTRUCTOR",
    DELETE_INSTRUCTOR_SUCCESS: "DELETE_INSTRUCTOR_SUCCESS",
    
    DELETE_STUDENT: "DELETE_STUDENT",
    DELETE_STUDENT_SUCCESS: "DELETE_STUDENT_SUCCESS",
    
    DELETE_COURSE: "DELETE_COURSE",
    DELETE_COURSE_SUCCESS: "DELETE_COURSE_SUCCESS",
    
    MENU_ADD: "MENU_ADD",
    MENU_DISPLAY: "MENU_DISPLAY",
    MENU_UPDATE: "MENU_UPDATE",
}

export default cst